### ISSUE TITLE
The meaning of some terms

### ISSUE THREAD

**Issue by RuoyuGuo** [emilwallner/How-to-learn-Deep-Learning#4]
In "Applied research/ research assistant/ residencies", there are 2 different multiplier types called "Readme" and "Write-up". Could you explain to me what they are in a project? 
Is the "readme" similar to "README.MD" in a repository?

**Comment by emilwallner** [comment]
Excellent feedback!! I made a few adjustments, let me know if it's better now. Also, let me know if there is anything else that is mildly confusing.

**Comment by RuoyuGuo** [comment]
Thank you much, your guide is really really helpful to me. Sorry, I am not a native English speaker, is there any difference between documentation and articles? For my understanding, they both aim to introduce your projects.

 I am a student studying in CS on a master of coursework degree currently and I plan to apply a master of research degree in CS in some universities. Besides, I am looking for some labs that are focusing on video, audio recognition, which are also my interesting areas. 

However, I don't know how to satisfy their requirements(or come to the level to become a research).
This is confusing me now... Such universities also need that you have your research plan and agreement from a professor. 

I know it is a good way if I could prepare some nice projects that are relevant to the professor's research. As you say, you could read some SOFA papers and try to implement them or look at some students projects in University that might give some inspiration. Besides... I don't know such places could see SOFA papers currently...

I mean, is that enough or there are more ways to do it?

Another of my question is how to come to the next level of ML when I finish some ML courses...

I appreciate you if you would like to spend time on these questions...

**Comment by emilwallner** [comment]
The goal of the documentation is for a technical audience to build on your work, the article is for a broader audience to understand how and why you built your project, as well as, creating evidence that you did the work.

Regardless of what you want to do, you want evidence that you can do the type of work they are already doing. If you are not sure of what to do or who to contact, email ~150 P.h.Ds in the area you are interested in and ask them for advice on projects to build. If you create something amazing, it's likely they'll introduce you to people that can benefit from your skillset. 

Start building things that you are interested in and that are strategic for your career path, document it well, and share your work. Good luck!!
