### ISSUE TITLE
Theory 101 [4 months] section - Youtube link doens't work

### ISSUE THREAD

**Issue by B8ni** [emilwallner/How-to-learn-Deep-Learning#6]
The **[#theory-101-4-months](https://github.com/emilwallner/How-to-learn-Deep-Learning#theory-101-4-months)** section,  link regarding "[great way to study the book](https://www.youtube.com/watch?v=bzp5bQY7XmE&list=PLh6SAYydrIpc8uCGc_KxjLSDRV6tfT10u&index=2)" doesn't work.

Is there any country restriction or just is anymore available? 

Tried to search on YT with same keywords but found nothing.

**Comment by emilwallner** [comment]
Thanks! Yeah, it looks like it's taken down. Here's a good [substitute](https://www.youtube.com/watch?v=vi7lACKOUao&list=PLsXu9MHQGs8df5A4PzQGw-kfviylC-R9b&ab_channel=AlenaKruchkova)
